In [54]:
import pandas as pd

In [55]:
path_segmentos_sku = "datos/Propuesta de productos a eliminar.xlsx"
segmentos_sku = pd.read_excel(path_segmentos_sku, sheet_name="BBDD")
segmentos_sku.head()

,SKU,Marca,Familia,Canal,Canal principal,Nombre Subfamilia,Nombre producto,Liquidación en tradicional,Kilos vendidos,Ingresos ('000 CLP),...,Margen2 ('000 CLP),Margen2 (%),Costos indirectos ('000 CLP),EBITDA ('000 CLP),EBITDA (%),Segmento Producto,Eliminable,Racional,Subfamilia,Delta Mg1 - EBITDA
0,3879.0,La Preferida,Snacks,TRADICIONAL,COBERTURA,Snackin (Snacks de Salame),CAJA SNACKIN SALAME 22X18GR LP,No,59985.997,1180958.470,...,510397.827732,0.432189,71533.295250,438864.532482,0.371617,Héroe,No,-,37.0,0.213048
1,3976.0,La Preferida,Snacks,SUPERMERCADO,SUPERMERCADO,Snackin (Snacks de Salame),BOLSA SNACKIN SALAME LP 50GR,No,17528.850,259573.055,...,109080.406766,0.420230,15785.245117,93295.161649,0.359418,Héroe,No,-,37.0,0.207337
2,3149.0,La Preferida,Pates,TRADICIONAL,COBERTURA,Paté Jamón/Salame/Ternera/Ave/Pollo,PASTA SALAME 8x125 GR LP,No,72163.780,347675.030,...,145727.673179,0.419149,22902.758336,122824.914843,0.353275,Héroe,No,-,32.0,0.358318
3,3154.0,La Preferida,Jamon G2,SUPERMERCADO,SUPERMERCADO,Jamón y Pechuga de Pavo G2,PECHUGA COCIDA PAVO CP 10x125 GR LP,No,8696.765,111027.568,...,45297.287999,0.407982,6673.512994,38623.775005,0.347876,Héroe,No,-,49.0,0.220725
4,3003.0,La Preferida,Jamon G2,TRADICIONAL,COBERTURA,Jamón y Pechuga de Pavo G2,JAMON SANDWICH DE PAVO LP,No,213637.540,1543491.426,...,626847.459911,0.406123,97748.359217,529099.100695,0.342794,Héroe,No,-,49.0,0.279122

In [56]:
segmentos_sku.columns

Index(['SKU', 'Marca', 'Familia', 'Canal', 'Canal principal',
       'Nombre Subfamilia', 'Nombre producto', 'Liquidación en tradicional',
       'Kilos vendidos', 'Ingresos ('000 CLP)', 'Costo directo ('000 CLP)',
       'Margen 1 ('000 CLP)', 'Margen1 (%)', 'Costos distribuibles ('000 CLP)',
       'Margen2 ('000 CLP)', 'Margen2 (%)', 'Costos indirectos ('000 CLP)',
       'EBITDA ('000 CLP)', 'EBITDA (%)', 'Segmento Producto', 'Eliminable',
       'Racional', 'Subfamilia', 'Delta Mg1 - EBITDA'],
      dtype='str')

In [57]:
path_infaltables = "datos/Base Infaltables.xlsx"
infaltables = pd.read_excel(path_infaltables)
infaltables.head()

,Año,Mes,Canal,AgrInfaltable,CodSKU,DesSKU,TipoNeg,Relev,NivPrecio,Ficha,OrdenAgr,OrdenSKU,Familia,Marca,CANAL,NEGOCIO,Tipo SKU
0,2026,4,MY,ARROLLADOS SJ,20,ARROLLADO LOMO CON AJI SJ,MA,1,B,FICHA MY,87,2,ARROLLADOS,SAN JORGE,MAYORISTA,MAYORISTA,Homologable
1,2026,4,MY,ARROLLADOS SJ,20,ARROLLADO LOMO CON AJI SJ,MA,1,E,FICHA MY,87,2,ARROLLADOS,SAN JORGE,MAYORISTA,MAYORISTA,Homologable
2,2026,4,MY,ARROLLADOS SJ,20,ARROLLADO LOMO CON AJI SJ,MA,1,S,FICHA MY,87,2,ARROLLADOS,SAN JORGE,MAYORISTA,MAYORISTA,Homologable
3,2026,4,MY,ARROLLADOS SJ,20,ARROLLADO LOMO CON AJI SJ,MA,2,B,FICHA MY,87,2,ARROLLADOS,SAN JORGE,MAYORISTA,MAYORISTA,Homologable
4,2026,4,MY,ARROLLADOS SJ,20,ARROLLADO LOMO CON AJI SJ,MA,2,E,FICHA MY,87,2,ARROLLADOS,SAN JORGE,MAYORISTA,MAYORISTA,Homologable

In [58]:
infaltables.columns

Index(['Año', 'Mes', 'Canal', 'AgrInfaltable', 'CodSKU', 'DesSKU', 'TipoNeg',
       'Relev', 'NivPrecio', 'Ficha', 'OrdenAgr', 'OrdenSKU', 'Familia',
       'Marca', 'CANAL', 'NEGOCIO', 'Tipo SKU'],
      dtype='str')

In [59]:
infaltables = infaltables[
    (infaltables["Canal"]=="CB") &
    (infaltables["Tipo SKU"]=="Infaltable")
]

In [60]:
skus_infaltables = infaltables["CodSKU"].unique()
print(len(skus_infaltables))
print(skus_infaltables)

25
[ 210  399  430  689  716 1020 1032 1228 1372 1404 2271 3018 3032 3071
 3142 3239 3313 3456 3519 3991 3996 6770 8299 8454 8508]

In [61]:
segmentos_sku["infaltable"] = segmentos_sku["SKU"].isin(skus_infaltables)

In [62]:
# Como se distribuyen los infaltables en los segmentos
segmentos_sku[
    (segmentos_sku["infaltable"])
]["Segmento Producto"].value_counts()

Segmento Producto
Héroe        18
Seguidor      5
Aprendiz      1
Emergente     1
Name: count, dtype: int64

In [63]:
# Como se distribuyen los heroes en los infaltables
segmentos_sku[
    (segmentos_sku["Segmento Producto"]=="Héroe")
]["infaltable"].value_counts()

infaltable
False    57
True     18
Name: count, dtype: int64

In [67]:
tabla_segmentacion_infaltables = (
    pd.crosstab(segmentos_sku["Segmento Producto"], segmentos_sku["infaltable"])
    .rename(columns={True: "Infaltable", False: "No infaltable"})
    .reindex(columns=["Infaltable", "No infaltable"], fill_value=0)
)

tabla_segmentacion_infaltables

infaltable         Infaltable  No infaltable
Segmento Producto
Aprendiz                    1             30
Emergente                   1             48
Héroe                      18             57
Rebelde                     0             18
Seguidor                    5             29
Villano                     0             24

Se han definido Productos Homologables, de manera de no afectar la ejecución en aquellos puntos de 
venta que no trabajan el formato exigible de los productos infaltables.

In [64]:
ingresos_heroes = segmentos_sku[
    (segmentos_sku["Segmento Producto"]=="Héroe")
]["Ingresos ('000 CLP)"].sum()
ingresos_heroes_infaltables = segmentos_sku[
    (segmentos_sku["Segmento Producto"]=="Héroe") &
    (segmentos_sku["infaltable"])
]["Ingresos ('000 CLP)"].sum()

print(f"Ingresos Heroes infaltables: {ingresos_heroes_infaltables}")
print(f"Ingresos Heroes: {ingresos_heroes}")
print(f"Esto significa un {ingresos_heroes_infaltables/ingresos_heroes * 100}%")

Ingresos Heroes infaltables: 47111498.264
Ingresos Heroes: 84612614.20300001
Esto significa un 55.67904822201986%

In [66]:
ebitda_heroes = segmentos_sku[
    (segmentos_sku["Segmento Producto"]=="Héroe")
]["EBITDA ('000 CLP)"].sum()
ebitda_heroes_infaltables = segmentos_sku[
    (segmentos_sku["Segmento Producto"]=="Héroe") &
    (segmentos_sku["infaltable"])
]["EBITDA ('000 CLP)"].sum()

print(f"Ingresos Heroes infaltables: {ebitda_heroes_infaltables}")
print(f"Ingresos Heroes: {ebitda_heroes}")
print(f"Esto significa un {ebitda_heroes_infaltables/ebitda_heroes * 100}%")

Ingresos Heroes infaltables: 10722254.579455163
Ingresos Heroes: 19830046.972768668
Esto significa un 54.07074725631941%

In [ ]:
villanos_infaltables = segmentos_sku[
    (segmentos_sku["infaltable"]) &
    (segmentos_sku["Segmento Producto"]=="Villano")
]["Nombre producto"].unique()

In [ ]:
anexo, poner de los infaltables, que es cada uno

In [ ]:
grafico de pau con margen 1 destacando infaltables

In [ ]:
cuantos de los heroes no son infaltables

In [ ]:
print(villanos_infaltables)

<StringArray>
[]
Length: 0, dtype: str