In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Explorar ventas

In [12]:
# Cargar datos de ventas
path_ventas = "datos/Ventas por Cliente/ventas_con_descuento_aplicado.csv"
ventas = pd.read_csv(path_ventas)

print("Ventas - Filas:", ventas.shape[0])
display(ventas.head())

/var/folders/dw/9r647bwd1kl_g5lxtz0kh4100000gp/T/ipykernel_12432/2649053988.py:3: DtypeWarning: Columns (0: dscto_volumen, 1: ids_descuento_volumen) have mixed types. Specify dtype option on import or set low_memory=False.
  ventas = pd.read_csv(path_ventas)

Ventas - Filas: 2157646

,cod_cliente,cod_canal_comercial,cod_consolidado,zona,distrito,fecha_factura,cod_sku,nombre_sku,monto_real,kilo_real,...,precio_lista_por_unidad,descuento_pct_observado,descuento_pct_matcheado,diferencia_descuento_pct,descuento_aplicado,id_descuento_aplicado,calza_con_descuento,gap,monto_a_precio_lista,costo_descuento
0,1227986,HR,37,SANTIAGO,SANTIAGO CENTRO COSTA,2026-02-16,3112,SALAME PIEZA 1KG LP,8274,1.0,...,8274.0,0.000000e+00,0.0,0.000000e+00,ninguno,NaN,False,False,8274.0,0.0
1,1176438,HR,37,NORTE 1,ANTOFAGASTA,2026-02-04,8512,"SALCHICHON CERVEZA WINTER 1,8 KG",108216,27.0,...,7214.4,-1.110223e-14,0.0,-1.110223e-14,ninguno,NaN,False,False,108216.0,0.0
2,1035323,CB,54,NORTE 2,SAN FELIPE,2026-02-16,3112,SALAME PIEZA 1KG LP,7033,1.0,...,8274.0,-1.499879e+01,0.0,-1.499879e+01,ninguno,NaN,False,True,8274.0,1241.0
3,1011205,CB,32,SUR 1,RANCAGUA,2026-02-16,3112,SALAME PIEZA 1KG LP,7033,1.0,...,8274.0,-1.499879e+01,0.0,-1.499879e+01,ninguno,NaN,False,True,8274.0,1241.0
4,1035323,CB,54,NORTE 2,SAN FELIPE,2026-02-09,8517,SALCHICHON CERVEZA MINI PZA 8x400 GR WI,22308,12.0,...,1486.8,-4.998655e+01,0.0,-4.998655e+01,liquidacion_forzado,NaN,False,True,44604.0,22296.0

In [13]:
canales_relevantes = [
    32,  # COBERTURA
    54,  # VOLUMEN COBERTURA
    # 67,  # MAYORISTAS CADENAS
    # 57,  # MAYORISTA B VOLUMEN
    # 38,  # OTROS MAYORISTAS
    # 55,  # HORECA VOLUMEN
    # 37,  # OTROS HORECA
]

ventas["fecha_factura"] = pd.to_datetime(ventas["fecha_factura"])

FECHA_FIN_DATOS_VENTAS = pd.Timestamp("2026-03-31")

ventas_relevantes = ventas[
    (ventas["cod_consolidado"].isin(canales_relevantes)) &
    (ventas["fecha_factura"] <= FECHA_FIN_DATOS_VENTAS)
]

In [14]:
SKU = 253
FECHA_INICIO_DSCTO = pd.Timestamp("2025-04-29")
FECHA_FIN_DSCTO = pd.Timestamp("2025-05-04")

ventas_periodo_dscto = ventas_relevantes[
    (FECHA_INICIO_DSCTO <= ventas_relevantes["fecha_factura"]) &
    (ventas_relevantes["fecha_factura"] <= FECHA_FIN_DSCTO)
]
ventas_periodo_sku = ventas_periodo_dscto[
    ventas_periodo_dscto["cod_sku"] == SKU
]
ventas_periodo_sku.head()

Empty DataFrame
Columns: [cod_cliente, cod_canal_comercial, cod_consolidado, zona, distrito, fecha_factura, cod_sku, nombre_sku, monto_real, kilo_real, precio_real, precio_lista, dscto_base, dscto_volumen, dscto_binario, carta_impacto, id_descuento_base, ids_descuento_volumen, id_descuento_binario, id_descuento_carta_impacto, año_factura, mes_factura, kg_por_unidad, peso_variable, cantidad_unidades, cantidad_unidades_entera, inconsistencia, precio_por_unidad, precio_lista_por_unidad, descuento_pct_observado, descuento_pct_matcheado, diferencia_descuento_pct, descuento_aplicado, id_descuento_aplicado, calza_con_descuento, gap, monto_a_precio_lista, costo_descuento]
Index: []

[0 rows x 38 columns]

# Explorar Descuentos

In [3]:
path_descuentos = "datos/Descuentos históricos/consolidado_descuentos.csv"
descuentos = pd.read_csv(path_descuentos)
print("Descuentos - Filas:", descuentos.shape[0])
display(descuentos.head())

Descuentos - Filas: 76509

,id_descuento,tipo_descuento,cod_sku,cod_canal,cod_consolidado,cod_cliente,fecha_inicio,fecha_fin,monto_descuento,__source_order
0,1,base,1006,CB,54.0,NaN,2026-03-02,2026-03-18,0.0,338
1,2,base,1006,CB,54.0,NaN,2026-03-19,9999-12-31,0.0,339
2,3,base,1006,HR,55.0,NaN,2026-03-02,2026-03-18,0.0,1118
3,4,base,1006,HR,55.0,NaN,2026-03-19,2026-03-29,0.0,1119
4,5,base,1006,HR,56.0,NaN,2023-11-01,2024-06-09,-24.8,1656

In [ ]:
descuentos[].shape[0]

69438

In [10]:
76509 - 69438

7071

In [13]:
descuentos[
    (descuentos["monto_descuento"]>0) &
    (descuentos["tipo_descuento"]!="carta_impacto")
]

,id_descuento,tipo_descuento,cod_sku,cod_canal,cod_consolidado,cod_cliente,fecha_inicio,fecha_fin,monto_descuento,__source_order
74372,74373,volumen,102,HR,56.0,NaN,2024-06-18,2024-06-20,10.0,2170
74373,74374,volumen,102,HR,56.0,NaN,2024-06-18,2024-06-20,15.0,2171
74374,74375,volumen,102,HR,56.0,NaN,2024-06-18,2024-06-20,20.0,2172

In [8]:
losquesaca= descuentos[~descuentos["cod_consolidado"].isin([32, 54])]

In [11]:
losquesaca[losquesaca["cod_consolidado"].isna()]

,id_descuento,tipo_descuento,cod_sku,cod_canal,cod_consolidado,cod_cliente,fecha_inicio,fecha_fin,monto_descuento,__source_order
44,45,base,1020,CB,NaN,NaN,2024-02-05,2024-02-29,-10.0,3643
4898,4899,carta_impacto,1006,NaN,NaN,1002215.0,2026-04-01,2026-04-10,2878.0,3422
4899,4900,carta_impacto,1006,NaN,NaN,1002667.0,2026-04-06,2026-04-10,2878.0,3629
4900,4901,carta_impacto,1006,NaN,NaN,1008117.0,2026-04-07,2026-04-10,2878.0,3732
4901,4902,carta_impacto,1006,NaN,NaN,1039197.0,2026-04-06,2026-04-10,2878.0,3975
...,...,...,...,...,...,...,...,...,...,...
74335,74336,carta_impacto,970,NaN,NaN,92024.0,2026-04-01,2026-04-30,3746.0,20539
75634,75635,volumen,6770,CB,NaN,NaN,2024-04-15,2024-04-25,-21.2,2179
75696,75697,volumen,6771,CB,NaN,NaN,2024-04-15,2024-04-25,-26.8,2180
75843,75844,volumen,689,CB,NaN,NaN,2024-05-12,2024-05-25,-20.0,2178
75844,75845,volumen,689,CB,NaN,NaN,2024-05-12,2024-05-25,-10.0,2177